services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Seccion1_Container
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: tail -f /dev/null
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mydb

  mysql:
    image: mysql:8.0
    container_name: Seccion1_DB
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
    ports:
      - "8010:8010"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
